#!/bin/sh
#

cd /tmp

wget -O- https://ghproxy.com/https://github.com/typecho/typecho/archive/refs/heads/master.tar.gz | tar xzf -
rm -rf /var/www/default && mv typecho-master /var/www/default

rm -rf /var/www/default/.g* rm -rf /var/www/default/.p*
rm -rf /var/www/default/*.md

sed -i "s/config.inc.php/usr\/config.php/g" /var/www/default/index.php
sed -i "s/config.inc.php/usr\/config.php/g" /var/www/default/install.php
sed -i "s/^define('__TYPECHO_ROOT_DIR__', dirname(__FILE__))/define('__TYPECHO_ROOT_DIR__', dirname(__DIR__))/" /var/www/default/install.php

rm -rf /tmp/*
