#!/bin/sh
#

cd /tmp

cp -a etc/* /etc/
chmod a+x /etc/wkit.d/*

rm -rf /var/www/default

# install and clean the typecho
wget -O- https://github.com/typecho/typecho/archive/refs/heads/master.tar.gz | tar xzf -
mv typecho-master /var/www/default && mv /var/www/default/usr /var/www/prepare
rm -rf /var/www/default/.g* /var/www/default/.p* /var/www/default/*.md

# auto save config.inc.php to usr/config.php
sed -i 's#return $code#file_put_contents(__TYPECHO_ROOT_DIR__ . "/usr/config.php", $code);\nreturn $code#' /var/www/default/install.php

rm -rf /tmp/*
